create table groups (
    groupid int not null auto_increment,
    groupname varchar(80) not null comment '群组名称',
    grouplink varchar(200) not null comment '群组链接',
    groupicon varchar(200) not null comment '群组图像链接',
    enabled TINYINT not null DEFAULT 0 comment '是否有效',
    seq TINYINT not null DEFAULT 0 comment '序列',
    deleted TINYINT not null DEFAULT 0 comment '已删陿?',
    createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updatetime TIMESTAMP NOT NULL  COMMENT '更新时间',

    constraint pk_groupid primary key (groupid)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='群列衿';

insert into groups values(500,'Gram 官方群','https://t.me/tgramplus','gram.jpg',1,0,0,now(),now());
insert into groups values(1,'Ripple XRP','https://t.me/Ripple','01-Ripple XRP.jpg',1,1,0,now(),now());
insert into groups values(2,'Binance English','https://t.me/binanceexchange','02-Binance-English.jpg',1,1,0,now(),now());
insert into groups values(3,'Litecoin LTC','https://t.me/Litecoin','03-Litecoin-LTC.jpg',1,1,0,now(),now());
insert into groups values(4,'Quantstamp','https://t.me/quantstamp','04-Quantstamp.jpg',1,1,0,now(),now());
insert into groups values(5,'Electroneum','https://t.me/electroneum','05-Electroneum.jpg',1,1,0,now(),now());
insert into groups values(6,'币安官方中文群','https://t.me/BinanceChinese','06-Official-Chinese-group-of-coins.jpg',1,1,0,now(),now());
insert into groups values(7,'DigiByte Official','https://t.me/DigiByteCoin','07-DigiByte-Official.jpg',1,1,0,now(),now());
insert into groups values(8,'CYBERMILES VIET NAM','https://t.me/cybermilesvn','08-CYBERMILES-VIET-NAM.jpg',1,1,0,now(),now());
insert into groups values(9,'Wavesnews and Announcements','https://t.me/wavesnews','09-Wavesnews-and-Announcements.jpg',1,1,0,now(),now());
insert into groups values(10,'CyberMiles','https://t.me/cybermilestoken ','10-CyberMiles.jpg',1,1,0,now(),now());
insert into groups values(11,'Omise GO (Unofficial))','https://t.me/OmiseGo','11-Omise-GO-(Unofficial).jpg',1,1,0,now(),now());
insert into groups values(12,'RaiBlocks Community','https://t.me/raiblockscommunity','12-RaiBlocks-Community.jpg',1,1,0,now(),now());
insert into groups values(13,'RaiBlocks (English chat)','https://t.me/raiblocks','13-RaiBlocks-(English-chat).jpg',1,1,0,now(),now());
insert into groups values(14,'QTUM','https://t.me/qtumofficial','14-QTUM.jpg',1,1,0,now(),now());
insert into groups values(15,'Civic Network Supporters','https://t.me/civicplatform','15-Civic-Network-Supporters.jpg',1,1,0,now(),now());
insert into groups values(16,'Quantstamp announcements','https://t.me/quantstampANN','16-Quantstamp-announcements.jpg',1,1,0,now(),now());
insert into groups values(17,'Bitshares DEX','://t.me/BitSharesDEX','17-Bitshares-DEX.jpg',1,1,0,now(),now());
insert into groups values(18,'VeChain Official English','https://t.me/vechain_official_english','18-VeChain-Official-English.jpg',1,1,0,now(),now());
insert into groups values(19,'EOS中文','https://t.me/EOSCN','19-EOS-Chinese.jpg',1,1,0,now(),now());
insert into groups values(20,'@Gold_Diamond93','https://t.me/Gold_Diamond93','20-@Gold_Diamond93.jpg',1,1,0,now(),now());
insert into groups values(21,'Kcash-CN','https://t.me/KcashOfficial','21-Kcash-CN.jpg',1,1,0,now(),now());
insert into groups values(22,'Enjin Coin (ENJ)','https://t.me/enjin_coin','22-Enjin-Coin-(ENJ).jpg',1,1,0,now(),now());
insert into groups values(23,'Cardano Community Trollbox - A','https://t.me/cardano','23-Cardano-Community-Trollbox-A.jpg',1,1,0,now(),now());
insert into groups values(24,'Monero XMR','https://t.me/monero','24-Monero-XMR.jpg',1,1,0,now(),now());
insert into groups values(25,'Monaco Card','https://t.me/MonacoCard','25-Monaco-Card.jpg',1,1,0,now(),now());
insert into groups values(26,'COBINHOOD','https://t.me/cobinhood','26-COBINHOOD.jpg',1,1,0,now(),now());
insert into groups values(27,'REGALCOIN OFFICIAL','https://t.me/regalcoinofficial','27-REGALCOIN-OFFICIAL.jpg',1,1,0,now(),now());
insert into groups values(28,'Skycoin - Building the new internet','https://t.me/Skycoin','28-Skycoin-Building-the-new-internet.jpg',1,1,0,now(),now());
insert into groups values(29,'Substratum Community','https://t.me/SubstratumCommunity','29-Substratum-Community.jpg',1,1,0,now(),now());
insert into groups values(30,'Siacoin SC','https://t.me/SiaCoin','30-Siacoin-SC.jpg',1,1,0,now(),now());
insert into groups values(31,'Bitcore_BTX','https://t.me/bitcore_btx_official','31-Bitcore_BTX.jpg',1,1,0,now(),now());
insert into groups values(32,'WAVE ART','https://t.me/waves_arts','32-WAVE-ART.jpg',1,1,0,now(),now());
insert into groups values(33,'SONM','https://t.me/sonm_eng','33-SONM.jpg',1,1,0,now(),now());
insert into groups values(34,'Cardano (ADA) Maingroup','https://t.me/CardanoMaingroup','34-Cardano-(ADA)-Maingroup',1,1,0,now(),now());
insert into groups values(35,'Huobi.pro-Official','https://t.me/huobiproofficial','35-Huobi.pro-Official.jpg',1,1,0,now(),now());
insert into groups values(36,'Cryptonex (CNX)','https://t.me/cryptonexCNX','36-Cryptonex-(CNX).jpg',1,1,0,now(),now());
insert into groups values(37,'Sυpєrทєτ 4G','https://t.me/Supernet4G','37-Sυpєrทєτ-4G.jpg',1,1,0,now(),now());
insert into groups values(38,'Achain','https://t.me/AchainOfficial','38-Achain.jpg',1,1,0,now(),now());
insert into groups values(39,'æternity','https://t.me/aeternity','39-æternity.jpg',1,1,0,now(),now());
insert into groups values(40,'CyberMiles繁体中文群','https://t.me/CyberMiles','40-CyberMiles-Traditional-Chinese-group.jpg',1,1,0,now(),now());
insert into groups values(41,'AdEx Network','https://t.me/adexnetwork','41-AdEx-Network.jpg',1,1,0,now(),now());
insert into groups values(42,'YobitPumpGroup','https://t.me/Yobit_Pump_Group','42-YobitPumpGroup.jpg',1,1,0,now(),now());
insert into groups values(43,'Reddcoin','https://t.me/ReddcoinOfficial','43-Reddcoin.jpg',1,1,0,now(),now());
insert into groups values(44,'Stratis Platform','https://t.me/StratisPlatform','44-Stratis-Platform.jpg',1,1,0,now(),now());
insert into groups values(45,'PayPie','https://t.me/PayPieTokens','45-PayPie.jpg',1,1,0,now(),now());
insert into groups values(46,'WINGS Chat','https://t.me/wingschat','46-WINGS-Chat.jpg',1,1,0,now(),now());
insert into groups values(47,'Presearch Community','https://t.me/presearch','47-Presearch-Community.jpg',1,1,0,now(),now());
insert into groups values(48,'Funfair FUN','https://t.me/FunFairTech','48-Funfair-FUN.jpg',1,1,0,now(),now());
insert into groups values(49,'NAV Coin','https://t.me/navcoin','49-NAV-Coin.jpg',1,1,0,now(),now());
insert into groups values(50,'Ethereum Centurion','https://t.me/Ethereum_Centurion','50-Ethereum-Centurion.jpg',1,1,0,now(),now());
insert into groups values(51,'Zcoin (XZC)','https://t.me/zcoinproject','51-Zcoin-(XZC).jpg',1,1,0,now(),now());
insert into groups values(52,'district0x','https://t.me/district0x','52-district0x.jpg',1,1,0,now(),now());
insert into groups values(53,'AirSwap Community','https://t.me/airswap','53-AirSwap-Community.jpg',1,1,0,now(),now());
insert into groups values(54,'Chainlink Community','https://t.me/chainlink','54-Chainlink-Community.jpg',1,1,0,now(),now());
insert into groups values(55,'ZEN','https://t.me/zencash','55-ZEN.jpg',1,1,0,now(),now());
insert into groups values(56,'Bitcoin Trading Signals','https://t.me/bitcoinsignals','56-Bitcoin-Trading-Signals.jpg',1,1,0,now(),now());
insert into groups values(57,'@Move to t.me/ethos_io','https://t.me/Bitquence','57-@Move-to-t.me-ethos_io.jpg',1,1,0,now(),now());
insert into groups values(58,'Substratum Link Portal','https://t.me/substratum','58-Substratum-Link-Portal.jpg',1,1,0,now(),now());
insert into groups values(59,'Monero Gold - XRG','https://t.me/monerogold_xrg','59-Monero-Gold-XRG.jpg',1,1,0,now(),now());
insert into groups values(60,'Viacoin','https://t.me/viacoin','60-Viacoin.jpg',1,1,0,now(),now());
insert into groups values(61,'Yobit pump group','https://t.me/yobits','61-Yobit-pump-group.jpg',1,1,0,now(),now());
insert into groups values(62,'SmartMesh Official','https://t.me/SmartMesh','62-SmartMesh-Official.jpg',1,1,0,now(),now());
insert into groups values(63,'Electroneum Cash','https://t.me/electroneumcash','63-Electroneum-Cash.jpg',1,1,0,now(),now());
insert into groups values(64,'Nuls Community','https://t.me/Nulsio','64-Nuls-Community.jpg',1,1,0,now(),now());
insert into groups values(65,'PayPie Announcements Channel','https://t.me/PayPie','65-PayPie-Announcements-Channel.jpg',1,1,0,now(),now());
insert into groups values(66,'Groestlcoin GRS','https://t.me/groestl','66-Groestlcoin-GRS.jpg',1,1,0,now(),now());
insert into groups values(67,'Komodo Platform Official','https://t.me/KomodoPlatform_Official','67-Komodo-Platform-Official.jpg',1,1,0,now(),now());
insert into groups values(68,'Coindash#Public','https://t.me/coindash','68-Coindash#Public.jpg',1,1,0,now(),now());
insert into groups values(69,'Peercoin >< Peercoin.chat','https://t.me/peercoin','69-Peercoin-Peercoin.chat.jpg',1,1,0,now(),now());
insert into groups values(70,'Steemit.com','https://t.me/steemitdotcom','70-Steemit.com.jpg',1,1,0,now(),now());
insert into groups values(71,'Vertcoin','https://t.me/VertcoinCrypto','71-Vertcoin.jpg',1,1,0,now(),now());

insert into groups values(72,'PotCoin','https://t.me/potcoin420','72-PotCoin.jpg',1,1,0,now(),now());
insert into groups values(73,'Loopring','https://t.me/loopringfans','73-Loopring.jpg',1,1,0,now(),now());
insert into groups values(74,'RaiBlocksID','https://t.me/raiblocksid','74-RaiBlocksID.jpg',1,1,0,now(),now());
insert into groups values(75,'流量矿石交流群','https://t.me/lltoken','75-Flow-ore-AC-group.jpg',1,1,0,now(),now());
insert into groups values(76,'比原链官方群','https://t.me/bytomchinese','76-Original-chain-official-group.jpg',1,1,0,now(),now());
insert into groups values(77,'BYTEBALL - telegram.me/byteball','https://t.me/byteball','77-BYTEBALL-telegram.me-byteball.jpg',1,1,0,now(),now());
insert into groups values(78,'Adex Trading (unofficial)','https://t.me/adex_trading','78-Adex-Trading-(unofficial).jpg',1,1,0,now(),now());
insert into groups values(79,'GameCredits','https://t.me/gamecreditsglobal','79-GameCredits.jpg',1,1,0,now(),now());
insert into groups values(80,'ICONOMI ICO','https://t.me/iconomi','80-ICONOMI-ICO.jpg',1,1,0,now(),now());
insert into groups values(81,'Bitcoin Indonesia『UNOFFICIAL』','https://t.me/Bitcoin_Indonesia','81-Bitcoin-Indonesia-UNOFFICIAL.jpg',1,1,0,now(),now());
insert into groups values(82,'VeChain 官方社区','https://t.me/vechain_officia_CN','82-VeChain-Official-Community.jpg',1,1,0,now(),now());
insert into groups values(83,'Metal Cult','https://t.me/metalcult','83-Metal-Cult.jpg',1,1,0,now(),now());
insert into groups values(84,'Чемпионат мира 2018','https://t.me/ticketsfootball','84-Чемпионат-мира-2018.jpg',1,1,0,now(),now());
insert into groups values(85,'Ethereum FundMe','https://t.me/EthereumFundMe','85-Ethereum-FundMe.jpg',1,1,0,now(),now());
insert into groups values(86,'// substratum ci //','https://t.me/substratumci','86-substratum-ci.jpg',1,1,0,now(),now());
insert into groups values(87,'Monacoin MONA','https://t.me/monacoin','87-Monacoin-MONA.jpg',1,1,0,now(),now());
insert into groups values(88,'Monacoin MONA','https://t.me/monacoin','88-Monacoin-MONA.jpg',1,1,0,now(),now());
insert into groups values(89,'※Upbit Pumping Room※','https://t.me/UpbitPumpingRoom','89-※Upbit-Pumping-Room※.jpg',1,1,0,now(),now());
insert into groups values(90,'Гороскоп БЛИЗНЕЦЫ','https://t.me/h_gemini','90-Гороскоп БЛИЗНЕЦЫ.jpg',1,1,0,now(),now());
insert into groups values(91,'Augur Project REP','https://t.me/AugurProject','91-Augur-Project-REP.jpg',1,1,0,now(),now());
insert into groups values(92,'æternity_cn','https://t.me/aeternity_cn','92-æternity_cn.jpg',1,1,0,now(),now());
insert into groups values(93,'Status Network Talk','https://t.me/StatusNetworkChat','93-Status-Network-Talk.jpg',1,1,0,now(),now());
insert into groups values(94,'Decred DCR','https://t.me/Decred','94-Decred-DCR.jpg',1,1,0,now(),now());
insert into groups values(95,'UPbit 코인 정보','https://t.me/UPbit','95-UPbit-코인-정보.jpg',1,1,0,now(),now());
insert into groups values(96,'Bitshares Traders Group','https://t.me/Bitshares_Traders','96-Bitshares-Traders-Group.jpg',1,1,0,now(),now());
insert into groups values(97,'Minexcoin','https://t.me/minexcoin','97-Minexcoin.jpg',1,1,0,now(),now());
insert into groups values(98,'Binance Coin','https://t.me/Binance','98-Binance-Coin.jpg',1,1,0,now(),now());
insert into groups values(99,'BitcoinStake','https://t.me/bitcoinstakecommunity','99-BitcoinStake.jpg',1,1,0,now(),now());
insert into groups values(100,'Cardano Announcement','https://t.me/CardanoAnnouncement','100-Cardano-Announcement.jpg',1,1,0,now(),now());
insert into groups values(101,'STORJ Russian Chat','https://t.me/storjRU','101-STORJ-Russian-Chat.jpg',1,1,0,now(),now());
insert into groups values(102,'Omise Go 中文讨论 (CN)','https://t.me/OmiseGoCN','102-Omise-Go-(CN).jpg',1,1,0,now(),now());
insert into groups values(103,'Counterparty XCP','https://t.me/Counterparty','103-Counterparty-XCP.jpg',1,1,0,now(),now());
insert into groups values(104,'The Verge','https://t.me/verge','104-The-Verge.jpg',1,1,0,now(),now());
insert into groups values(105,'Крипто сигналы','https://t.me/BittrexF','105-Крипто-сигналы.jpg',1,1,0,now(),now());
insert into groups values(106,'Gridcoin','https://t.me/gridcoin','106-Gridcoin.jpg',1,1,0,now(),now());
insert into groups values(107,'코인원 ETH 가격알림','https://t.me/coinone_eth','107-코인원-ETH-가격알림.jpg',1,1,0,now(),now());
insert into groups values(108,'Factom FCT','https://t.me/FactomFCT','108-Factom-FCT.jpg',1,1,0,now(),now());
insert into groups values(109,'MAIDSAFECOIN MAID','https://t.me/maidsafecoin','109-MAIDSAFECOIN-MAID.jpg',1,1,0,now(),now());
insert into groups values(110,'Cofound.it.','https://t.me/cofounditchat','110-Cofound.it.jpg',1,1,0,now(),now());
insert into groups values(111,'Electroneums - UNOFFICIAL','https://t.me/electroneums','111-Electroneums-UNOFFICIAL.jpg',1,1,0,now(),now());
insert into groups values(112,'Nuls中文社区','https://t.me/Nulscn','112-Nuls-Chinese-community.jpg',1,1,0,now(),now());
insert into groups values(113,'Bancor [RU]','https://t.me/Bancor_RU','113-Bancor-[RU].jpg',1,1,0,now(),now());
insert into groups values(114,'LiveCoinWatch.com Cryptocurrency Group','https://t.me/livecoinwatch','114-LiveCoinWatch.com-Cryptocurrency-Group.jpg',1,1,0,now(),now());
insert into groups values(115,'Delphy天算官方交流群','https://t.me/Delphyfans','115-Delphy-Official-communication-group.jpg',1,1,0,now(),now());
insert into groups values(116,'Ubiq','https://t.me/Ubiqsmart','116-Ubiq.jpg',1,1,0,now(),now());
insert into groups values(117,'Bytecoin','https://t.me/Bytecoin','117-Bytecoin.jpg',1,1,0,now(),now());
insert into groups values(118,'COINEGG官方中文群','https://t.me/coineggofficial','118-COINEGG-Official-Chinese-group.jpg',1,1,0,now(),now());
insert into groups values(119,'Pillar Project','https://t.me/pillarproject','119-Pillar-Project.jpg',1,1,0,now(),now());
insert into groups values(120,'Veritaseum','https://t.me/veritaseum','120-Veritaseum.jpg',1,1,0,now(),now());
insert into groups values(121,'Streamr DATA','https://t.me/streamrdata','121-Streamr-DATA.jpg',1,1,0,now(),now());
insert into groups values(122,'Populous','https://t.me/Populous','122-Populous.jpg',1,1,0,now(),now());
insert into groups values(123,'HitBTC Pumpers','https://t.me/HitBTCPumpers','123-HitBTC-Pumpers.jpg',1,1,0,now(),now());
insert into groups values(124,'COBINHOOD零手续费交易所','https://t.me/COBINHOOD_ZH','124-COBINHOOD-Zero-handling-exchange.jpg',1,1,0,now(),now());
insert into groups values(125,'BtcTrade.im中文官方群','https://t.me/btctradeofficial','125-BtcTrade.im-Chinese-official-group.jpg',1,1,0,now(),now());
insert into groups values(126,'Dragonex用户交流群','https://t.me/Dragonex_io','126-Dragonex-User-exchange-group.jpg',1,1,0,now(),now());
insert into groups values(127,'district0x Network','https://t.me/district0xNetwork','127-district0x-Network.jpg',1,1,0,now(),now());
insert into groups values(128,'OTN - Open Trading Network','https://t.me/opentn','128-OTN-Open-Trading-Network.jpg',1,1,0,now(),now());
insert into groups values(129,'MediShares Info Channel','https://t.me/medishares','129-MediShares-Info-Channel.jpg',1,1,0,now(),now());
insert into groups values(130,'ReddCoinRU (RDD)','https://t.me/ReddCoinRU','130-ReddCoinRU-(RDD).jpg',1,1,0,now(),now());
insert into groups values(131,'FirstBlood Official Telegram','https://t.me/firstbloodio','131-FirstBlood-Official-Telegram.jpg',1,1,0,now(),now());
insert into groups values(132,'Skycoin Bounty Program','https://t.me/skycoinbounty','132-Skycoin-Bounty-Program.jpg',1,1,0,now(),now());
insert into groups values(133,'æternity [RU]','https://t.me/aeternityRU','133-æternity-[RU].jpg',1,1,0,now(),now());
insert into groups values(134,'Melonport','https://t.me/melonport','134-Melonport.jpg',1,1,0,now(),now());
insert into groups values(135,'流量矿石官方交流群','https://t.me/lltoken_com','135-Official-exchange-group-of-flow-ore.jpg',1,1,0,now(),now());
insert into groups values(136,'Oh my tickets!','https://t.me/Oh_my_tickets','136-Oh-my-tickets.jpg',1,1,0,now(),now());
insert into groups values(137,'Ubiquiti Networks - Brasil','https://t.me/ubiquitibr','137-Ubiquiti-Networks-Brasil.jpg',1,1,0,now(),now());
insert into groups values(138,'Skycoin News','https://t.me/skycoinnews','138-Skycoin-News.jpg',1,1,0,now(),now());
insert into groups values(139,'Decentraland Korea','https://t.me/decentralandkorea','139-Decentraland-Korea.jpg',1,1,0,now(),now());
insert into groups values(140,'Blocknet','https://t.me/Blocknet','140-Blocknet.jpg',1,1,0,now(),now());
insert into groups values(141,'Official Counterparty Chat','https://t.me/Counterparty_XCP','141-Official-Counterparty-Chat.jpg',1,1,0,now(),now());
insert into groups values(142,'Syscoin','https://t.me/syscoin','142-Syscoin.jpg',1,1,0,now(),now());
insert into groups values(143,'Delphy天算官方公告栏','https://t.me/DelphyBulletinBoard','143-Delphy-days-official-bulletin-board.jpg',1,1,0,now(),now());
insert into groups values(144,'Syscoin KR','https://t.me/SyscoinOfficialKR','144-Syscoin-KR.jpg',1,1,0,now(),now());
insert into groups values(145,'LinkEye Chinese','https://t.me/LinkEyeProject','145-LinkEye-Chinese.jpg',1,1,0,now(),now());
insert into groups values(146,'Poloniex Trollbox2!','https://t.me/poloniex2','146-Poloniex-Trollbox2.jpg',1,1,0,now(),now());
insert into groups values(147,'SiacoinRU (SC)','https://t.me/SiacoinRU','147-SiacoinRU-(SC).jpg',1,1,0,now(),now());
insert into groups values(148,'金牛财经JinNiu.cn','https://t.me/jinniu','148-Taurus-Finance-JinNiu.cn.jpg',1,1,0,now(),now());
insert into groups values(149,'Iconomi ICN Español','https://t.me/IconomiES','149-Iconomi-ICN-Español.jpg',1,1,0,now(),now());
insert into groups values(150,'Siacoin SC 中文讨论 (CN)','https://t.me/SiacoinCN','150-Siacoin-SC-(CN).jpg',1,1,0,now(),now());
insert into groups values(151,'Coinfix','https://t.me/CoinfixOfficial','151-Coinfix.jpg',1,1,0,now(),now());
insert into groups values(152,'SelfSell_CN','https://t.me/SelfSell','152-SelfSell_CN.jpg',1,1,0,now(),now());
insert into groups values(153,'莱特币社区','https://t.me/litecoin1','153-LTC.jpg',1,1,0,now(),now());
insert into groups values(154,'Geld, Gold, Bitcoin','https://t.me/geld_gold_bitcoin','154-Geld-Gold- Bitcoin.jpg',1,1,0,now(),now());
insert into groups values(155,'BTC Gold','https://t.me/bitcoin_gold','155-BTC-Gold.jpg',1,1,0,now(),now());
insert into groups values(156,'Ethereum Classic','https://t.me/ethereum_classic_official','156-Ethereum-Classic.jpg',1,1,0,now(),now());
insert into groups values(157,'Ethereum Classic Mining Pool: etc-pool.com','https://t.me/ethereum_classic_pool','157-Ethereum -Classic Mining Pool-etc-pool-com.jpg',1,1,0,now(),now());
insert into groups values(158,'NEO Blockchain','https://t.me/Neo_Blockchain','158-NEO-Blockchain.jpg',1,1,0,now(),now());
insert into groups values(159,'Stellar Lumens','https://t.me/stellar_lumens_brasil','159-Stellar-Lumens.jpg',1,1,0,now(),now());
insert into groups values(160,'Bitcoin buy and sell','https://t.me/bitconnect','160-Bitcoin-buy-and-sell.jpg',1,1,0,now(),now());
insert into groups values(161,'MagicCoin Việt Nam','https://t.me/magiccoinvn','161-MagicCoin-Việt-Nam.jpg',1,1,0,now(),now());
insert into groups values(162,'Tethereum original','https://t.me/tethereum','162-TethereuM-original.jpg',1,1,0,now(),now());
insert into groups values(163,'Zcash','https://t.me/ZcashCoin','163-Zcash.jpg',1,1,0,now(),now());
insert into groups values(164,'Z.cash','https://t.me/zcash','164-Z.cash.jpg',1,1,0,now(),now());
insert into groups values(165,'Stratis CN','https://t.me/StratisCN','165-Stratis-CN.jpg',1,1,0,now(),now());
insert into groups values(166,'Hshare','https://t.me/Hsharebot','166-Hshare.jpg',1,1,0,now(),now());
insert into groups values(167,'Ardor','https://t.me/ardorchina','167-Ardor.jpg',1,1,0,now(),now());
insert into groups values(168,'Ardorplatform','https://t.me/ardorgroup','168-Ardorplatform.jpg',1,1,0,now(),now());
insert into groups values(169,'Bytecoin BCN','https://t.me/bytecoinchat','169-Bytecoin-BCN.jpg',1,1,0,now(),now());
insert into groups values(170,'Steemit Russian Community','https://t.me/steemit','170-Steemit-Russian-Community.jpg',1,1,0,now(),now());
insert into groups values(171,'DECRED [BR]','https://t.me/decredbr','171-DECRED-[BR].jpg',1,1,0,now(),now());
insert into groups values(172,'EMC2','https://t.me/EinsteiniumFoundation','172-EMC2.jpg',1,1,0,now(),now());
insert into groups values(173,'Augur','https://t.me/Augurbot','173-Augur.jpg',1,1,0,now(),now());
insert into groups values(174,'绿币中文讨论 Vertcoin CN','https://t.me/VertcoinCN','174-Vertcoin-CN.jpg',1,1,0,now(),now());
insert into groups values(175,'Komodo Trading Group','https://t.me/komodoplatform','175-Komodo-Trading-Group.jpg',1,1,0,now(),now());
insert into groups values(176,'DogeCoin Token','https://t.me/dogecoin_token','176-DogeCoin-Token.jpg',1,1,0,now(),now());
insert into groups values(177,'퍼스트 코인 firstcoin','https://t.me/firstcoinkorea','177-firstcoin.jpg',1,1,0,now(),now());
insert into groups values(178,'Digix DAO','https://t.me/DigixDAO','178-Digix-DAO.jpg',1,1,0,now(),now());
insert into groups values(179,'WTC华文国际交流群','https://t.me/waltonchain_cn','179-waltonchain_cn.jpg',1,1,0,now(),now());
insert into groups values(180,'KyberNetWork','https://t.me/Kyber_NetWork','180-KyberNetWork.jpg',1,1,0,now(),now());
insert into groups values(181,'Basic Attention Token Russia','https://t.me/batrussia','181-Basic-Attention-Token-Russia.jpg',1,1,0,now(),now());
insert into groups values(182,'Syscoin','https://t.me/SyscoinOfficial','182-Syscoin.jpg',1,1,0,now(),now());
insert into groups values(183,'Byteball','https://t.me/ByteballTG','183-Byteball.jpg',1,1,0,now(),now());
insert into groups values(184,'Decentraland','https://t.me/decentraland','184-Decentraland.jpg',1,1,0,now(),now());
insert into groups values(185,'Decentraland','https://t.me/Decentralandbot','185-Decentraland.jpg',1,1,0,now(),now());
insert into groups values(186,'HyperPay（Unofficial)','https://t.me/HyperPay','186-HyperPay-Unofficial).jpg',1,1,0,now(),now());
insert into groups values(187,'Zcoin(XZC)中国社区','https://t.me/Zcoinchina','187-Zcoin(XZC).jpg',1,1,0,now(),now());
insert into groups values(188,'Bytom announcement','https://t.me/bytomannouncement','188-Bytom-announcement.jpg',1,1,0,now(),now());
insert into groups values(189,'Regalcoin Official','https://t.me/regalcoin','189-Regalcoin-Official.jpg',1,1,0,now(),now());
insert into groups values(190,'ICOnomical (ru channel)','https://t.me/iconomical_ru','190-ICOnomical-(ru channel).jpg',1,1,0,now(),now());
insert into groups values(191,'VeChain Coin','https://t.me/VeChain','191-VeChain-Coin.jpg',1,1,0,now(),now());
insert into groups values(192,'GAMECREDITS ESPAÑOL','https://t.me/gamecreditspanish','192-GAMECREDITS-ESPAÑOL.jpg',1,1,0,now(),now());
insert into groups values(193,'GameCredits','https://t.me/gamecredits','193-GameCredits.jpg',1,1,0,now(),now());
insert into groups values(194,'Gnosis-Cristiana','https://t.me/gnosiscristiana','194-Gnosis-Cristiana.jpg',1,1,0,now(),now());
insert into groups values(195,'Genaro中国社区','https://t.me/dragonchaincommunitysale','195-Genaro.jpg',1,1,0,now(),now());
insert into groups values(196,'BQX','https://t.me/bitquencetoken','196-BQX.jpg',1,1,0,now(),now());
insert into groups values(197,'B3coin','https://t.me/b3coinOfficial','197-B3coin.jpg',1,1,0,now(),now());
insert into groups values(198,'Minexcoin (RU)','https://t.me/minexcoinru','198-Minexcoin-(RU).jpg',1,1,0,now(),now());
insert into groups values(199,'Minexcoin BRPT','https://t.me/minexcoinpt','199-Minexcoin-BRPT.jpg',1,1,0,now(),now());
insert into groups values(200,'Metaverse $ETP','https://t.me/etpmetaverse','200-Metaverse-$ETP.jpg',1,1,0,now(),now());
insert into groups values(201,'NAV Coin CN','https://t.me/navcoincn','201-NAV-Coin-CN.jpg',1,1,0,now(),now());
insert into groups values(202,'Storjx ITA','https://t.me/storjitalian','202-Storjx-ITA.jpg',1,1,0,now(),now());
insert into groups values(203,'Storj','https://t.me/storj','203-Storj.jpg',1,1,0,now(),now());
insert into groups values(204,'Minexcoin (RU)','https://t.me/minexcoinru','204-Minexcoin-(RU).jpg',1,1,0,now(),now());
insert into groups values(205,'Minexcoin BRPT','https://t.me/minexcoinpt','205-Minexcoin-BRPT.jpg',1,1,0,now(),now());
insert into groups values(206,'Metaverse $ETP','https://t.me/etpmetaverse','206-Metaverse-$ETP.jpg',1,1,0,now(),now());
insert into groups values(207,'Peercoin China','https://t.me/PeercoinCN','207-Peercoin-China.jpg',1,1,0,now(),now());
insert into groups values(208,'Peercoin Russia','https://t.me/PeercoinRU','208-Peercoin-Russia.jpg',1,1,0,now(),now());
insert into groups values(209,'BitBays','https://t.me/bitbays','209-BitBays.jpg',1,1,0,now(),now());
insert into groups values(210,'BitBay Market - Trading Talk','https://t.me/bitbaytradingtalk','210-BitBay-Market-Trading-Talk.jpg',1,1,0,now(),now());
insert into groups values(211,'Lykke Dev','https://t.me/LykkeDev','211-Lykke-Dev.jpg',1,1,0,now(),now());
insert into groups values(212,'حُـضْـنٰ | ᏰᏦℭ','https://t.me/jinn3','212-JINN3.jpg',1,1,0,now(),now());
insert into groups values(213,'Particl [PART] News','https://t.me/particlnews','213-Particl-[PART]-News.jpg',1,1,0,now(),now());
insert into groups values(214,'particl','https://t.me/particl','214-particl.jpg',1,1,0,now(),now());
insert into groups values(215,'Groestlcoin','https://t.me/Groestlcoin','215-Groestlcoin.jpg',1,1,0,now(),now());
insert into groups values(216,'SingularDTV','https://t.me/singulardtvnews','216-SingularDTV.jpg',1,1,0,now(),now());
insert into groups values(217,'SingularDTV - Blockchain based Entertainment Studio','https://t.me/singulardtv','217-SingularDTV-Blockchain-based-Entertainment-Studio.jpg',1,1,0,now(),now());
insert into groups values(218,'Zencash solo','https://t.me/zencashsolo','218-Zencash-solo.jpg',1,1,0,now(),now());
insert into groups values(219,'Zencash España','https://t.me/zencashesp','219-Zencash-España.jpg',1,1,0,now(),now());
insert into groups values(220,'Quantstamp 2','https://t.me/quantstamp2','220-Quantstamp-2.jpg',1,1,0,now(),now());
insert into groups values(221,'流量矿石交流群','https://t.me/lltokencom','221-lltokencom.jpg',1,1,0,now(),now());
insert into groups values(222,'Feathercoin Official','https://t.me/FeathercoinOfficial','222-Feathercoin-Official.jpg',1,1,0,now(),now());
insert into groups values(223,'Feathercoin','https://t.me/feathercoin','223-Feathercoin.jpg',1,1,0,now(),now());
insert into groups values(224,'Basic Attention Token Russia','https://t.me/batrussia','224-Basic-Attention-Token-Russia.jpg',1,1,0,now(),now());
insert into groups values(225,'Loopring','https://t.me/loopringorg','225-Loopring.jpg',1,1,0,now(),now());
insert into groups values(226,'路印协议','https://t.me/loopring','226-LRC.jpg',1,1,0,now(),now());
insert into groups values(227,'YOYOW公告','https://t.me/YOYOW_announcements','227-YOYOW-INFO.jpg',1,1,0,now(),now());
insert into groups values(228,'yoyow123','https://t.me/yoyow123','228-yoyow123.jpg',1,1,0,now(),now());
insert into groups values(229,'Aragón News','https://t.me/AragonNews','229-Aragón-News.jpg',1,1,0,now(),now());
insert into groups values(230,'ARAGON France #ANT','https://t.me/ARAGONfr','230-ARAGON-France-#ANT.jpg',1,1,0,now(),now());
insert into groups values(231,'Ripio Credit Network','https://t.me/RCNtaIk','231-Ripio-Credit-Network.jpg',1,1,0,now(),now());
insert into groups values(232,'Ripio Credit Network (TOKENSALE)','https://t.me/RCNTokenSale','232-Ripio-Credit-Network-(TOKENSALE).jpg',1,1,0,now(),now());
insert into groups values(233,'Potcoin','https://t.me/Potcoin','233-Potcoin.jpg',1,1,0,now(),now());
insert into groups values(234,'PotCoin','https://t.me/PotCoins','234-PotCoin.jpg',1,1,0,now(),now());
insert into groups values(235,'COBINHOOD — Биржа с нулевой комиссией','https://t.me/COBINHOOD_RU','235-COBINHOOD_RU.jpg',1,1,0,now(),now());
insert into groups values(236,'FairCoin Launch Updates','https://t.me/FairCoinLaunchUpdates','236-FairCoin-Launch-Updates.jpg',1,1,0,now(),now());
insert into groups values(237,'Faircoin','https://t.me/faircoin','237-Faircoin.jpg',1,1,0,now(),now());
insert into groups values(238,'MobileGo','https://t.me/mobilego','238-MobileGo.jpg',1,1,0,now(),now());
insert into groups values(239,'MobileGoRussia','https://t.me/mobilegoru','239-MobileGoRussia.jpg',1,1,0,now(),now());
insert into groups values(240,'Hshs','https://t.me/mobilegol','240-Hshs.jpg',1,1,0,now(),now());
insert into groups values(241,'Quantum Resistant Ledger','https://t.me/qrledger','241-Quantum-Resistant-Ledger.jpg',1,1,0,now(),now());
insert into groups values(242,'Trump Dojo','https://t.me/counterpartyxcp','242-Trump-Dojo.jpg',1,1,0,now(),now());
insert into groups values(243,'PayPie Español','https://t.me/PayPie_ES','243-PayPie-Español.jpg',1,1,0,now(),now());
insert into groups values(244,'AEON','https://t.me/AEONgroup','244-AEON.jpg',1,1,0,now(),now());
insert into groups values(245,'Aeon Coin Supporters','https://t.me/AeonCoin','245-Aeon-Coin-Supporters.jpg',1,1,0,now(),now());
insert into groups values(246,'WeTrust','https://t.me/wetrust_ico','246-WeTrust.jpg',1,1,0,now(),now());
insert into groups values(247,'SONM Public Rus','https://t.me/sonm_rus','247-SONM-Public-Rus.jpg',1,1,0,now(),now());
insert into groups values(248,'WINGS OF FIRE','https://t.me/wingsoffire','248-WINGS-OF-FIRE.jpg',1,1,0,now(),now());
insert into groups values(249,'Mercury Protocol','https://t.me/MercuryProtocol','249-Mercury-Protocol.jpg',1,1,0,now(),now());
insert into groups values(250,'MERCURY GLOBAL 2017','https://t.me/MERCURY_GLOBAL_2017','250-MERCURY-GLOBAL-2017 .jpg',1,1,0,now(),now());
insert into groups values(251,'ITC','https://t.me/IoTChain','251-ITC.jpg',1,1,0,now(),now());
insert into groups values(252,'iExec RLC','https://t.me/iExecRLC','252-iExec-RLC.jpg',1,1,0,now(),now());
insert into groups values(253,'Neblio','https://t.me/neblio','253-Neblio.jpg',1,1,0,now(),now());
insert into groups values(254,'Neblio','https://t.me/nebliotoken','254-Neblio.jpg',1,1,0,now(),now());
insert into groups values(255,'MCAProTraining','https://t.me/MCAProTraining','255-MCAProTraining.jpg',1,1,0,now(),now());
insert into groups values(256,'mCapture4u','https://t.me/mCapture','256-mCapture4u.jpg',1,1,0,now(),now());
insert into groups values(257,'reddcoin','https://t.me/reddcoin','257-reddcoin.jpg',1,1,0,now(),now());
insert into groups values(258,'Enigma Protocol + Catalyst','https://t.me/enigmacatalyst','258-Enigma-Protocol+Catalyst.jpg',1,1,0,now(),now());
insert into groups values(259,'EnigmaCatalyst 中文交流群','https://t.me/EnigmaCatalystCN','259-EnigmaCatalyst-cn.jpg',1,1,0,now(),now());
insert into groups values(260,'NameCoin NMC','https://t.me/NameCoin','260-NameCoin-NMC.jpg',1,1,0,now(),now());
insert into groups values(261,'Emercoin','https://t.me/emercoin','261-Emercoin.jpg',1,1,0,now(),now());
insert into groups values(262,'EMC - Emercoin','https://t.me/emc_emercoin','262-EMC-Emercoin.jpg',1,1,0,now(),now());
insert into groups values(263,'Emercoin','https://t.me/Emercoinbot','263-Emercoin.jpg',1,1,0,now(),now());
insert into groups values(264,'Tickets','https://t.me/tickets','264-Tickets.jpg',1,1,0,now(),now());
insert into groups values(265,'VoxelStorm Announce','https://t.me/VoxelStorm','265-VoxelStorm-Announce.jpg',1,1,0,now(),now());
insert into groups values(266,'AirSwap Official','https://t.me/airswapofficial','266-AirSwap-Official.jpg',1,1,0,now(),now());
insert into groups values(267,'宙斯盾官方中文交流群','https://t.me/Zeusshieldoff','267-Zeusshieldoff.jpg',1,1,0,now(),now());
insert into groups values(268,'Zeusshield','https://t.me/Zeusshield','268-Zeusshield.jpg',1,1,0,now(),now());
insert into groups values(269,'Tierion','https://t.me/tierion','269-Tierion.jpg',1,1,0,now(),now());
insert into groups values(270,'Tierion_China','https://t.me/tierion_china','270-Tierion_China.jpg',1,1,0,now(),now());
insert into groups values(271,'BLOCKv Token Sale RUS','https://t.me/blockv_rus','271-BLOCKv-Token-Sale-RUS.jpg',1,1,0,now(),now());
insert into groups values(272,'Blockvis','https://t.me/blockvis','272-Blockvis.jpg',1,1,0,now(),now());
insert into groups values(273,'Cofound.it news','https://t.me/cofounditnews','273-Cofound.it-news.jpg',1,1,0,now(),now());
insert into groups values(274,'Super Netfree','https://t.me/SuperNetfree','274-Super-Netfree.jpg',1,1,0,now(),now());
insert into groups values(275,'NLG Gulden - Community','https://t.me/guldentalk','275-NLG-Gulden-Community.jpg',1,1,0,now(),now());
insert into groups values(276,'Gulden NLG (unofficial)','https://t.me/GuldenNederland','276-Gulden-NLG-(unofficial).jpg',1,1,0,now(),now());
insert into groups values(277,'Gulden','https://t.me/gulden','277-Gulden.jpg',1,1,0,now(),now());
insert into groups values(278,'Сибирский Червонец','https://t.me/sibcoin_ru','278-Сибирский-Червонец.jpg',1,1,0,now(),now());
insert into groups values(279,'Сибирский Червонец','https://t.me/sibcoin','279-Сибирский-Червонец.jpg',1,1,0,now(),now());
insert into groups values(280,'SIBCoin (Siberian Chervonec)','https://t.me/sibcoin_en','280-SIBCoin-(Siberian-Chervonec).jpg',1,1,0,now(),now());
insert into groups values(281,'Wagerr','https://t.me/Wagerrr','281-Wagerr.jpg',1,1,0,now(),now());
insert into groups values(282,'Wagerr Turkish Chat Group','https://t.me/wagerrtr','282-Wagerr-Turkish-Chat-Group.jpg',1,1,0,now(),now());
insert into groups values(283,'CloakCoin','https://t.me/CloakCoin','283-CloakCoin.jpg',1,1,0,now(),now());
insert into groups values(284,'DECENT','https://t.me/decentchina','284-DECENT.jpg',1,1,0,now(),now());
insert into groups values(285,'Decentraland','https://t.me/decentraland','285-Decentraland.jpg',1,1,0,now(),now());
insert into groups values(286,'whitecoin','https://t.me/whitecoin','286-whitecoin.jpg',1,1,0,now(),now());
insert into groups values(287,'Initial_Coin_Offering','https://t.me/Initial_Coin_Offering','287-Initial_Coin_Offering.jpg',1,1,0,now(),now());
insert into groups values(288,'CoinDash China','https://t.me/coindashchina','288-CoinDash-China.jpg',1,1,0,now(),now());
insert into groups values(289,'Coindash Korea','https://t.me/CoindashKorea','289-Coindash-Korea.jpg',1,1,0,now(),now());
insert into groups values(290,'Enjin Coin恩金币华语官方','https://t.me/enjin_coin_chinese','290-enjin_coin_chinese.jpg',1,1,0,now(),now());
insert into groups values(291,'Bitcore_BTX_Ukraine','https://t.me/bitcoreukraine','291-Bitcore_BTX_Ukraine.jpg',1,1,0,now(),now());
insert into groups values(292,'Bit Core','https://t.me/bitcore','292-Bit-Core.jpg',1,1,0,now(),now());
insert into groups values(293,'Paypex','https://t.me/paypex','293-Paypex.jpg',1,1,0,now(),now());
insert into groups values(294,'Safe Exchange Coin','https://t.me/Safex_Exchange','294-Safe-Exchange-Coin.jpg',1,1,0,now(),now());
insert into groups values(295,'Smartcash RU','https://t.me/smartcashru','295-Smartcash-RU.jpg',1,1,0,now(),now());
insert into groups values(296,'SmartCashInvest','https://t.me/SmartCashbot','296-SmartCashInvest.jpg',1,1,0,now(),now());
insert into groups values(297,'Presearch News','https://t.me/presearchnews','297-Presearch News.jpg',1,1,0,now(),now());
insert into groups values(298,'Unlimited IPTV','https://t.me/UnlimitedIPTV','298-Unlimited-IPTV.jpg',1,1,0,now(),now());
insert into groups values(299,'Numeraire','https://t.me/Numerairebot','299-Numeraire.jpg',1,1,0,now(),now());
insert into groups values(300,'NoLimitCoin','https://t.me/NoLimitCoin','300-NoLimitCoin.jpg',1,1,0,now(),now());
insert into groups values(301,'district0xbot (name is reserved)','https://t.me/district0xbot','301-district0xbot-(name-is-reserved).jpg',1,1,0,now(),now());
insert into groups values(302,'LBRY Credits','https://t.me/LBRYcredits','302-LBRY-Credits.jpg',1,1,0,now(),now());
insert into groups values(303,'LBRY Credits Channel','https://t.me/Lbrycredit','303-LBRY-Credits-Channel.jpg',1,1,0,now(),now());
insert into groups values(304,'OKCashAnnouncement','https://t.me/OKCashAnnouncement','304-OKCashAnnouncement.jpg',1,1,0,now(),now());
insert into groups values(305,'ipchain','https://t.me/ipchain','305-ipchain.jpg',1,1,0,now(),now());
insert into groups values(306,'IPCHAIN News','https://t.me/ipchainnews','306-IPCHAIN-News.jpg',1,1,0,now(),now());
insert into groups values(307,'Первый кровавый','https://t.me/firstblooder','307-Первый-кровавый.jpg',1,1,0,now(),now());
insert into groups values(308,'i DOTA 2','https://t.me/FirstBlood','308-i-DOTA-2.jpg',1,1,0,now(),now());
insert into groups values(309,'Bithumb TrollBox','https://t.me/bithumbtrollbox','309-Bithumb-TrollBox.jpg',1,1,0,now(),now());
insert into groups values(310,'빗썸_비트렉스 coinpool.kr','https://t.me/bithumb_bittrex','310-bithumb_bittrex.jpg',1,1,0,now(),now());
insert into groups values(311,'Bitfinex网','https://t.me/Bitfinex_INT','311-Bitfinex_INT.jpg',1,1,0,now(),now());
insert into groups values(312,'Bitmex Rekt Relay','https://t.me/BitmexRekt','312-Bitmex-Rekt-Relay.jpg',1,1,0,now(),now());
insert into groups values(313,'Bittrex','https://t.me/Bittrex','313-Bittrex.jpg',1,1,0,now(),now());
insert into groups values(314,'Bittrex best signals ™','https://t.me/bittrexsignals','314-Bittrex-best-signals™.jpg',1,1,0,now(),now());
insert into groups values(315,'CoinChecker.info','https://t.me/CoinChecker_info_Rus','315-CoinChecker.info.jpg',1,1,0,now(),now());
insert into groups values(316,'코인원 XRP 가격알림','https://t.me/coinone_xrp','316-coinone_xrp.jpg',1,1,0,now(),now());
insert into groups values(317,'OKEx官方中文群正版','https://t.me/okexofficial_cn','317-okexofficial_cn.jpg',1,1,0,now(),now());
insert into groups values(318,'Hitbtc TrollBox!','https://t.me/HitbtcTrollBox','318-Hitbtc-TrollBox.jpg',1,1,0,now(),now());
insert into groups values(319,'BitFlyer','https://t.me/BitFlyer','319-BitFlyer.jpg',1,1,0,now(),now());
insert into groups values(320,'Crypto currencies','https://t.me/poloniex','320-Crypto-currencies.jpg',1,1,0,now(),now());
insert into groups values(321,'Poloniex Increase(CoinfoBox)','https://t.me/coinfobox_for_poloniex','321-Poloniex-Increase(CoinfoBox).jpg',1,1,0,now(),now());
insert into groups values(322,'BitStamp','https://t.me/bitstamp','322-BitStamp.jpg',1,1,0,now(),now());
insert into groups values(323,'Quoinex trading talking','https://t.me/quoinex','323-Quoinex-trading-talking.jpg',1,1,0,now(),now());
insert into groups values(324,'国池矿工群','https://t.me/BTCChinaPool','324-BTCChinaPool.jpg',1,1,0,now(),now());
insert into groups values(325,'coinnest','https://t.me/coinnest','325-coinnest.jpg',1,1,0,now(),now());
insert into groups values(326,'CoinsBank ITA','https://t.me/CoinsBankITA','326-CoinsBank-ITA.jpg',1,1,0,now(),now());
insert into groups values(327,'Cex.io','https://t.me/cex_io','327-Cex.io.jpg',1,1,0,now(),now());
insert into groups values(328,'Bitcoin','https://t.me/bitcoin_zh','328-Bitcoin.jpg',1,1,0,now(),now());
insert into groups values(329,'币赢～海外ico交流群','https://t.me/coinwin','329-coinwin.jpg',1,1,0,now(),now());
insert into groups values(330,'eBTCbank交流群','https://t.me/eBTCbank','330-eBTCbank.jpg',1,1,0,now(),now());
insert into groups values(331,'BitBay Market Korea','https://t.me/bitbayofficialkorea','331-BitBay-Market-Korea.jpg',1,1,0,now(),now());
insert into groups values(332,'Paribu','https://t.me/paribu','332-Paribu.jpg',1,1,0,now(),now());
insert into groups values(333,'Liqui中国玩家群','https://t.me/liquichina','333-Liquichina.jpg',1,1,0,now(),now());
insert into groups values(334,'YOEXS','https://t.me/yoexs','334-YOEXS.jpg',1,1,0,now(),now());

insert into groups values(499,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,0,0,now(),now());
insert into groups values(499,'Gram 官方群','https://t.me/tgramplus','gram.jpg',1,0,0,now(),now());
insert into groups values(500,'Gram 官方群1','https://t.me/tgramplus2','gram.jpg',1,0,0,now(),now());
insert into groups values(501,'Gram 官方群','https://t.me/tgramplus','gram.jpg',1,0,0,now(),now());


insert into groups values(498,'创投峰会','https://t.me/block2018club','blog_tech.jpg',1,0,0,now(),now());
insert into groups values(498,'极速路演','https://t.me/block2018club','jisu.jpeg',1,0,0,now(),now());


insert into groups values(700,'Athena中文群','https://t.me/AthenaCN','eos_chat.jpg',1,2,0,now(),now());
insert into groups values(701,'Athena英文群','https://t.me/AthenaEN','eos_chat.jpg',1,2,0,now(),now());

insert into groups values(699,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,2,0,now(),now());

insert into groups values(799,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,3,0,now(),now());
insert into groups values(899,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,4,0,now(),now());
insert into groups values(999,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,5,0,now(),now());

insert into groups values(559,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,6,0,now(),now());
insert into groups values(569,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,7,0,now(),now());
insert into groups values(579,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,8,0,now(),now());


insert into groups values (161,'EOS中文群','https://t.me/EOSCN','19-EOS-Chinese.jpg',1,0,0,now(),now());

insert into groups values (300,'AthenaCN','https://t.me/AthenaCN','eos_chat.jpg',1,2,0,now(),now());
insert into groups values (301,'AthenaEN','https://t.me/AthenaEN','eos_chat.jpg',1,2,0,now(),now());
insert into groups values (400,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,3,0,now(),now());
insert into groups values (401,'EON官方群','https://t.me/EONOfficialCN','156-EONOfficialCN.jpg',1,3,0,now(),now());
insert into groups values (402,'火星财经','https://t.me/huoxing24','161-huoxing24.jpg',1,3,0,now(),now());
insert into groups values (500,'EON官方群','https://t.me/EONOfficialCN','161-huoxing24.jpg',1,4,0,now(),now());
insert into groups values (600,'EOS官方群','https://t.me/EOSproject','https://t.me/EOSproject',1,5,0,now(),now());
insert into groups values (601,'EOS中文群','https://t.me/EOSCN','19-EOS-Chinese.jpg',1,5,0,now(),now());
insert into groups values (700,'币安中文群','https://t.me/Binance_cn','157-Binance_cn.jpg',1,6,0,now(),now());
insert into groups values (701,'火币中文群','https://t.me/huobiofficial','158-huobiofficial.jpg',1,6,0,now(),now());
insert into groups values (702,'OKEX中文群','https://t.me/OKExauthority','159-OKExauthority.jpg',1,6,0,now(),now());
insert into groups values (703,'ZB中文群','https://t.me/ZB_support','160-ZB_support.jpg',1,6,0,now(),now());
insert into groups values (800,'布洛克科技','https://t.me/BlockTechnologyPRO','blog_tech.jpg',1,7,0,now(),now());
insert into groups values (801,'火星财经','https://t.me/huoxing24','161-huoxing24.jpg',1,7,0,now(),now());